CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL UNIQUE,
  `nickname` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `chatbot_token` INT NOT NULL DEFAULT 1000,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `terminals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner_id` BIGINT UNSIGNED NOT NULL,
  `template_id` BIGINT UNSIGNED NOT NULL,
  `container_name` VARCHAR(64) NOT NULL,
  `container_size` DECIMAL(7, 2) NOT NULL,
  `total_duration` TIME NOT NULL DEFAULT '00:00:00',
  `remark` VARCHAR(1024),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `terminal_templates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(64) NOT NULL,
  `image_size` DECIMAL(7, 2) NOT NULL,
  `description` VARCHAR(1024),
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

