# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_pty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61se_pty.proto\"\x1c\n\rRunCmdRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\" \n\x0eRunCmdResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2:\n\x07\x42\x61sePty\x12/\n\x06RunCmd\x12\x0e.RunCmdRequest\x1a\x0f.RunCmdResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RUNCMDREQUEST']._serialized_start=18
  _globals['_RUNCMDREQUEST']._serialized_end=46
  _globals['_RUNCMDRESPONSE']._serialized_start=48
  _globals['_RUNCMDRESPONSE']._serialized_end=80
  _globals['_BASEPTY']._serialized_start=82
  _globals['_BASEPTY']._serialized_end=140
# @@protoc_insertion_point(module_scope)
