// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"
)

type Terminal struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Size          string    `json:"size"`
	Remark        string    `json:"remark"`
	OwnerID       int64     `json:"ownerID"`
	TemplateID    int64     `json:"templateID"`
	TotalDuration int32     `json:"totalDuration"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type TerminalTemplate struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	ImageName   string    `json:"imageName"`
	Size        string    `json:"size"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type User struct {
	ID               int64          `json:"id"`
	Email            string         `json:"email"`
	Nickname         string         `json:"nickname"`
	Password         string         `json:"password"`
	ChatbotToken     int32          `json:"chatbotToken"`
	VerificationCode sql.NullString `json:"verificationCode"`
	ExpiredAt        sql.NullTime   `json:"expiredAt"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}
